version: '3'
name: alpine_edge-prod

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpine_edge.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.alpine_edge.entrypoints=websecure"
      - "traefik.http.routers.alpine_edge.tls=true"
      - "traefik.http.routers.alpine_edge.tls.certresolver=letsencrypt"
    network_mode: bridge
    restart: always

# docker compose up -d
