name: Run gh-pages deploy

on:
  push:
    branches: [ master ]
      
env:
  CI: "false"
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build

    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build

